::: cv

See my full CV [here (pdf)](files/DG_cv_202505.pdf){.paper-link}.

Short CV
------

### Personal Information


**Nationality:** Hungarian\
**Research interests:** combinatorial rigidity theory, structural graph theory, matroid theory, discrete geometry, (applied)
algebraic geometry.\
**Email:** [daniel.garamvolgyi@ttk.elte.hu](mailto:daniel.garamvolgyi@ttk.elte.hu)\
**ORCID:** <https://orcid.org/0000-0002-8468-6585>\
**Arxiv ID:** <https://arxiv.org/a/0000-0002-8468-6585>\
**Google Scholar:** <https://scholar.google.com/citations?user=fx_EDksAAAAJ>\ 

::: professional

### Professional Experience

- January -- May 2025: **Semester Postdoc**, [ICERM](https://icerm.brown.edu/), Providence
- January -- August 2025:  **Research Fellow**, [Alfréd Rényi Institute of Mathematics](https://renyi.hu/en), Budapest
- September 2024 -- August 2025: **Research Associate**, [MTA-ELTE Matroid Optimization Research Group](https://berkri.web.elte.hu/memmorg/), Budapest
- September 2023 -- December 2024: **Predoctoral Fellow**, [Alfréd Rényi Institute of Mathematics](https://renyi.hu/en), Budapest
- September 2020 -- March 2024: **Research Assistant**, [Egerváry Research Group on Combinatorial Optimization](https://egres.elte.hu/), Budapest

:::

::: education

### Education

- 2019 -- 2025: **PhD in Mathematics**, Eötvös Loránd University, Budapest\
    Supervisor: Tibor Jordán &nbsp; &nbsp; &nbsp;  Grade: *summa cum laude*\
    Thesis title: **Unique reconstruction problems in rigidity theory** ([slides](/files/202412_defense.pdf){.slide-link} of defense talk)
- 2016 -- 2019: **MSc in Mathematics**, Eötvös Loránd University, Budapest\
    GPA: 5.0/5.0, graduated with honors\
    Thesis title: **Unlabeled graph realizability**
- 2013 -- 2016: **BSc in Mathematics**, Eötvös Loránd University, Budapest\
    GPA: 4.8/5.0, graduated with honors\
    Thesis title: [Factor of i.i.d. processes and regular graphs](https://web.cs.elte.hu/blobs/diplomamunkak/bsc_mat/2016/garamvolgyi_daniel.pdf){.paper-link}

:::

### Awards and Grants

<!-- - July 2024: [Research-in-Groups](https://www.icms.org.uk/funding-opportunities/research-groups-rigs) -->
- September 2024: **HUN-REN Mobility Program** travel grant
- December 2023: **Géza Grünwald Commemorative Prize** of the János Bolyai Mathematical Society
- January 2023: **Focus Program on Geometric Constraint Systems** travel grant
- 2019, 2021, 2022: **New National Excellence Programme (ÚNKP)** research grant
- 2018 – 2021: **Human Resources Development Operational Programme (EFOP)** scholarship


:::